### ISSUE TITLE
Integration with Web Stomp

### ISSUE THREAD

**Issue by VinayNadig** [rabbitmq/rabbitmq-auth-backend-http#12]
Hello,

We are using rabbitmq_web_stomp plugin with stomp.js & sock.js to connect to the RMQ broker. We are using the username & password as the means of authentication. But it looks like the authentication bypasses this plugin completely and connects with the provided credentials without making a call to configured auth endpoints.

Is there any configuration required or is it possible to use this plugin with the web stomp plugin?

Thanks

**Comment by michaelklishin** [comment]
So connection from Sock.js authenticates in a way that ignores the configured backend, is my understanding correct?

**Comment by VinayNadig** [comment]
Yes, that is correct. Is there any way that this can be changed?

**Comment by michaelklishin** [comment]
I find it hard to believe that WebSTOMP bypasses our internal authentication API. Need to take a look.

**Comment by bradjorgensen** [comment]
I'm using this plugin for auth and web-stomp and it is working as expected.
