### ISSUE TITLE
Authentication Failure Error

### ISSUE THREAD

**Issue by JayeshLunkad** [rabbitmq/rabbitmq-auth-backend-http#13]
Hi,

I have downloaded the bin of the plugin " rabbitmq_auth_backend_http-3.5.x-fe9401c6.ez" and put it into the plugins folder.
and then enabled the plugin . It shown configuration changed .
But when i start my server it doesnt start with the authentication plugin.

Server startup complete; 6 plugins started.
 * amqp_client
 * mochiweb
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch
 * webmachine

and when i send message to server from client the error report contains
=ERROR REPORT==== 30-Jun-2015::10:51:29 ===
closing AMQP connection <0.332.0> (127.0.0.1:42348 -> 127.0.0.1:5672):
{handshake_error,starting,0,
    {error,undef,'connection.start_ok',
        [{rabbit_auth_backend_http,check_user_login,
             [<<"guest">>,[{password,<<"guest">>}]],
             []},
         {rabbit_access_control,'-check_user_login/2-fun-0-',4,
             [{file,"src/rabbit_access_control.erl"},{line,56}]},
         {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},
         {rabbit_reader,auth_phase,2,
             [{file,"src/rabbit_reader.erl"},{line,987}]},
         {rabbit_reader,handle_method0,3,
             [{file,"src/rabbit_reader.erl"},{line,826}]},
         {rabbit_reader,handle_input,3,
             [{file,"src/rabbit_reader.erl"},{line,738}]},
         {rabbit_reader,recvloop,2,
             [{file,"src/rabbit_reader.erl"},{line,292}]},
         {rabbit_reader,run,1,[{file,"src/rabbit_reader.erl"},{line,273}]}]}}

Thanks

**Comment by michaelklishin** [comment]
Questions belong to rabbitmq-users.
