### ISSUE TITLE
Remove dependency on mochiweb in master

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-auth-backend-http#19]
This plugin depends on mochiweb because of a single function: `mochiweb_util:quote_plus/1`. In 3.7.0 we are moving away from Webmachine/Mochiweb so this extra dependency is unnecessary and should be removed.

**Comment by essen** [comment]
Also needs to be done on stable.

**Comment by michaelklishin** [comment]
@essen is this still relevant? should we try to get it into `3.7.0`?

**Comment by michaelklishin** [comment]
I don't see any Mochiweb dependencies (probably since https://github.com/rabbitmq/rabbitmq-management/issues/236) in this repo any more. @essen please reopen if I have missed something.
