### ISSUE TITLE
Use HTTP Keepalive

### ISSUE THREAD

**Issue by bradjorgensen** [rabbitmq/rabbitmq-auth-backend-http#20]
Would it be possible to have this plugin use HTTP keepalive?  It would be nice to have for performance in general and also reduce connection churning leading to a potentially high number of TIME_WAIT connections.

**Comment by hairyhum** [comment]
`http` already use keepalive by default. Default timeout is 2 min.

**Comment by bradjorgensen** [comment]
I looked into the code some after writing the initial issue and saw that it is explicitly using HTTP 1.0 and according to the erlang documentation, when using HTTP 1.0, keepalives are not used.

**Comment by michaelklishin** [comment]
Fixed in https://github.com/rabbitmq/rabbitmq-auth-backend-http/pull/22.
