### ISSUE TITLE
Are client IPs passed through to the webserver?

### ISSUE THREAD

**Issue by borodiansky** [rabbitmq/rabbitmq-auth-backend-http#24]
I see client IPs within the rabbit logs once clients connect, but I haven't discovered anything in the HTTP headers during auth/requests.  Is it possible to pass those through/retrieve them?

Thanks a lot

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. Authentication and authorization in RabbitMQ are typically  built around usernames, somy guess is no.

There is an authz plugin that uses IP addresses.
