### ISSUE TITLE
custom headers support

### ISSUE THREAD

**Issue by arjunasuresh3** [rabbitmq/rabbitmq-auth-backend-http#26]
I am using webstomp with this module for custom authentication. I am not getting custom-header in the auth url request. Is this suported?

stomp code 
var headers = {
                        login: 'username',
                        passcode: 'password',
                        // additional header
                        'custom-header': 'myclientid'
                    };
stompClient.connect(headers, STOMPAPI.on_connect, STOMPAPI.on_error);

rabbit config
[
  {rabbit, [{auth_backends, [rabbit_auth_backend_http]}]},
  {rabbitmq_auth_backend_http,
  [{user_path,     "http://localhost/apirabbit"},
    {vhost_path,    "http://localhost/apirabbit"},
    {resource_path, "http://localhost/apirabbit"}]
}].

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users in the future.

This plugin does not propagate all headers, in fact, some protocols RabbitMQ supports do not allow for arbitrary headers at all.
