### ISSUE TITLE
Support HTTPS backends (apps)

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-auth-backend-http#29]
We currently assume HTTP:
https://github.com/rabbitmq/rabbitmq-auth-backend-http/blob/master/src/rabbit_auth_backend_http.erl#L92.

This plugin is meant to be used in a trusted environment but [some attempt using it over HTTPS on the public Internet](https://groups.google.com/forum/#!topic/rabbitmq-users/KuIJGqxmPGU). So I guess it's worth adding.

**Comment by AdamMiltonBarker** [comment]
No environment is trusted, encryption is a must, also how come simonmacmullen  stated it would work perfectly fine using https:// .  I think I will give AMQP a miss until the fundamentals are in place. Just out of interest how are you suggesting that the plugin can communicate with a URL and be trusted if not using SSL.

**Comment by michaelklishin** [comment]
@AdamMiltonBarker I have no idea where Simon had stated that. For an HTTP client to be able to issue requests to an HTTPS server it has to have a certificate/key pair, worry about which certificates are trusted, and so on. This plugin doesn't do that at the moment, so I'm not sure how it would encrypt anything.

It is possible to use [stunnel](https://www.stunnel.org/index.html) to encrypt any TLS connection. "The fundamentals" are in place: RabbitMQ [supports TLS](http://rabbitmq.com/ssl.html) for every protocol it supports and inter-node links, only this particular plugin doesn't.

**Comment by AdamMiltonBarker** [comment]
Was going of his reply here,

https://github.com/rabbitmq/rabbitmq-auth-backend-http/issues/3

Yes it would need to access the trusted certs store on the server. I have TLS implemented on my version of Rabbit but it still opens up an insecure port as well despite specifically not telling it to in the configs. OK let me know if you get this implemented please. Do you know of any other plugins that I can implement that will allow authentication based on a SQL database. It is a specific requirement if it is not possible I will have to come back to AMQP at a later date, was hoping to implement it though.

**Comment by michaelklishin** [comment]
@AdamMiltonBarker you [absolutely can disable plain TCP connections](http://www.rabbitmq.com/networking.html) for every messaging protocol and HTTP API/management UI.

I'm not aware of community plugins that authenticate using a SQL database. Pivotal only provides this one, a LDAP one, and an x509 certificate-based authentication mechanism.

**Comment by AdamMiltonBarker** [comment]
Ok will check that out thanks, in the config I set it to open only secure port but it ignores this. So is the reason that the plugin is not hitting the script because it is on a secure URL ? Maybe @simonmacmullen could let me know why he thinks it would?

**Comment by michaelklishin** [comment]
@AdamMiltonBarker Wireshark or an HTTP tracer that supports TLS traffic decryption can tell. Lets not turn this issue into a support thread, our team doesn't use GitHub issues for that.

**Comment by michaelklishin** [comment]
HTTP client TLS options support was added in #32, will be in `3.6.2`.
