### ISSUE TITLE
Implement SSL

### ISSUE THREAD

**Issue by jar349** [rabbitmq/rabbitmq-auth-backend-http#3]
Simon,

I love this plugin and want to use it, but my production environment would require SSL so that no one can place a man-in-the-middle between your plugin and my auth web service.

Any idea when you might be able to spike that bit out?

Thanks!

**Comment by develar** [comment]
It is wrong way. Correct way — use docker and link your auth service to rabbitmq. So, service will not be exposed to. Then you can you tutum (private network is encrypted and requires authentication; only nodes belonging to a specific account can connect and communicate with each other. — http://blog.tutum.co/2015/03/03/introducing-overlay-networking-for-containers-and-dynamic-links-in-tutum/) or setup your own weave (https://github.com/zettio/weave, traffic could be encrypted).
