### ISSUE TITLE
Support for customized URLs?

### ISSUE THREAD

**Issue by mattfox75** [rabbitmq/rabbitmq-auth-backend-http#6]
I just started looking at this plug in for use in our system, and it appears that the URLs that the plug uses are fixed.  They simply use the server IP/name in the configuration and then performs a GET against port 8000 on that server at a predefined URL.  Is there any way to customize these URLs so we have better control over where on our server the plugin will make requests?

**Comment by uvzubovs** [comment]
If we start on the path of configuring URLs, we would then be configuring what requests and responses look like. It may be easier to just put a proxy between the plugin and the authn server to bridge the protocols.
