### ISSUE TITLE
rabbit_auth_backend_http or rabbitmq_auth_backend_http?

### ISSUE THREAD

**Issue by edsamonte** [rabbitmq/rabbitmq-auth-backend-http#65]
README.md seems a little confusing for beginners like me.

I tried to install RabbitMQ on Mac via brew and I tried enabling this plugin. I keep running:
```sh
$ rabbitmq-plugins enable rabbit_auth_backend_http
```

But apparently (upon running `rabbitmq-plugins list`) it should be:
```sh
$ rabbitmq-plugins enable rabbitmq_auth_backend_http
```

It is not enabled by default so I settled to do that command. 

Just ignore this if I'm just misunderstanding the README.md. Thanks.

**Comment by michaelklishin** [comment]
The README never mentions the name of the plugin, only module name in the classic config format. We will add a line that explains how to enable it.

**Comment by edsamonte** [comment]
Awesome! Thanks, @michaelklishin
