### ISSUE TITLE
Make POST requests instead of GET

### ISSUE THREAD

**Issue by sergray** [rabbitmq/rabbitmq-auth-backend-http#7]
Hi,

It would be great to change GET requests to POST, because GET requests expose passwords in access logs of web server serving the app for rabbitmq auth backend.

**Comment by deemytch** [comment]
+

**Comment by johnfoldager** [comment]
+1

**Comment by uvzubovs** [comment]
+1
Absolutely required or cannot use in the enterprise where http access is logged

**Comment by AdamMiltonBarker** [comment]
+1

**Comment by michaelklishin** [comment]
`GET` is still used in `3.6.x` for backwards compatibility. We might want to switch to `POST` by default in `3.7.0`.

**Comment by AdamMiltonBarker** [comment]
How come this is closed if it is not solved ? This is a clear security flaw

**Comment by michaelklishin** [comment]
@AdamMiltonBarker this is solved, see #30 which is merged. Like I said, we cannot change the default for `3.6.x` because it will break this plugin for all existing users.

**Comment by AdamMiltonBarker** [comment]
Ok tanks for letting me know will check it out, been away from the AMQP whilst focusing on some features of MQTT, will check out the linked issue, thanks for the reply.
