### ISSUE TITLE
auth/topic endpoint called twice

### ISSUE THREAD

**Issue by rozaydin** [rabbitmq/rabbitmq-auth-backend-http#72]
Hello,

We are using the auth-backend-http along with mqtt plugin, everything is working fine, but we realized one thing.  Whenever we sent an MQTT "Subscribe" or "Publish" the auth-backend-http is sending request to **/auth/topic** endpoint twice with **same contents**. Is there a specific reason why its doing this ? 

You can find a wireshark capture from the machine, and a screenshot attached.

![duplicate](https://user-images.githubusercontent.com/11554756/45426658-814d8380-b6a5-11e8-881a-5261c8559f21.png)

[duplicate-msgs-pcap.zip](https://github.com/rabbitmq/rabbitmq-auth-backend-http/files/2375218/duplicate-msgs-pcap.zip)

Thanks is advance

**Comment by michaelklishin** [comment]
I don't think it's intentional but without a way to reproduce I would rather not speculate. Can you provide a way to reproduce?

Also, in practice this plugin is used together with [rabbitmq-auth-backend-cache](https://github.com/rabbitmq/rabbitmq-auth-backend-cache) which masks this behavior entirely.

**Comment by lukebakken** [comment]
I can reproduce this and am investigating why.

**Comment by michaelklishin** [comment]
@rozaydin our working theory is that the MQTT plugin performs at least two operations when you begin consuming since it has to check for queue existence (and thus establish whether there's an existing session state). In that case it is expected that two authorization checks are performed.

**Comment by lukebakken** [comment]
@michaelklishin @rozaydin - yep, that is what is happening. [This is the code that executes for a new subscription](https://github.com/rabbitmq/rabbitmq-mqtt/blob/v3.7.7/src/rabbit_mqtt_processor.erl#L201-L249). Notice [here](https://github.com/rabbitmq/rabbitmq-mqtt/blob/v3.7.7/src/rabbit_mqtt_processor.erl#L836) that topic authorization is checked, and then the queue is declared and consumed from [here](https://github.com/rabbitmq/rabbitmq-mqtt/blob/v3.7.7/src/rabbit_mqtt_processor.erl#L712-L714), which will cause another check. I've attached a trace here:

[trace.txt](https://github.com/rabbitmq/rabbitmq-auth-backend-http/files/2376337/trace.txt)

Please use the cache backend to "resolve" this issue. Thanks!
