### ISSUE TITLE
Routing requests for different virtual hosts to different endpoints

### ISSUE THREAD

**Issue by devansharora68** [rabbitmq/rabbitmq-auth-backend-http#96]
Hello

**Raising this issue regarding below discussion thread in rabbitmq-users group** 
[Http auth backend for multi vhost environments](https://groups.google.com/forum/#!msg/rabbitmq-users/djlV32OnARw/WnE8hCqkAQAJ)

**Problem statement :** 

We are using rabbitmq auth backend http to authenticate rabbit users. In multi tenant(vhost) environments, We have different dedicated servers to authenticate different vhost`s users.
Like vhost01  auth requests should be authenticated by server01 and  vhost2 auth requests should be authenticated by server02. 

In rabbitmq config file we define a proxy url to send auth http requests. In our proxy currently, we read the http get request params to route the request to correct backend servers(server01, server02)
Like when vhost param value is "vhost01", route the request to "server01" backend server. when vhost param value is "vhost02"  route the request to "server02" backend server.

This according to our architects is not a safe approach and when using ssl we need to offload such ssl requests at our proxy server which takes up computation cycle.
Can we have a mechanism so that we can have vhost value in our http request url itself. So that we our able to route requests using url path to appropriate backend servers(server01, server02).

**Comment by michaelklishin** [comment]
I'm not convinced this is a common enough scenario. This plugin's responsibility is to post some data to a service, and if you need to route requests for different servers to different backends (sounds like what most people DO NOT do these days), that service can do it, and use proxies and/or TLS termination at any step that makes sense.

@acogoluegnes @lukebakken I'm leaning towards a `wontfix`. WDYT?

**Comment by devansharora68** [comment]
can we just allow to parameterize url of auth backend for post type requests

Like  user_path = https://ahost1:8080/auth/user/{vhost}
I could then just redirect using url using my proxy.

**Comment by michaelklishin** [comment]
That would be a lot more flexible and interesting. Please file a new issue with a more detailed description of how you envision that work.

**Comment by devansharora68** [comment]
Thanks 
Raised this [Vhost as a Path parameter for http auth backend #97](https://github.com/rabbitmq/rabbitmq-auth-backend-http/issues/97)
